---
title: "Spatial_plot"
author: "Katharine Keogan"
date: "09/04/2021"
output:
---

```{r spatialplot, include = FALSE}
i_sp <- gsub(" ", "_", i)

plot.list <- list()

SppDat <- SppDat[which(!is.na(SppDat$lat)),]

leg_dat <- dplyr::filter(SppDat, Species == i, yr == yrs[k], loc == locs[j])

for(m in 1:length(unique(SppDat$month))){

SppDatSPP <- dplyr::filter(SppDat, Species == i, month == unique(SppDat$month)[m], yr == yrs[k], loc == locs[j])

if(dim(SppDatSPP)[1] == 0){
spatialplot <- ggplot() +  
  #geom_tile(data=NULL, aes(x=NULL, y=NULL, fill=NULL), alpha= NULL) +
  geom_polygon(aes(x = long, y = lat, group = group), data = shapefileDF,fill="grey80",  
               col = "black") +
  geom_polygon(aes(x = long, y = lat, group = group), data = shapefileDF,fill=NA,  
               col = "black") +
  labs(fill = "Height (m)",x="",y="")+
  coord_equal() +
  ggthemes::theme_map()+
  ggtitle(unique(SppDat$month)[m]) +
  theme(legend.position="none",
        #legend.title = element_blank(),
        plot.title = element_text(size = 12, face = "bold", colour = "black"),
        axis.title = element_text(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        plot.margin = unit(c(0,-0.5,0,-0.5), unit = "cm")
  )
}else{

data_mod <- SppDatSPP
names(data_mod)[which(names(data_mod)=="lat")] <- "Lat"
names(data_mod)[which(names(data_mod)=="lon")] <- "Lon"


rr <- produce.raster(data_mod,p,
                     month=NULL,grd.density=50000,
                     idp=3.0, crs=sf::st_crs(4326)$proj4string)

pointdat <- data.frame(rr$dmodt)
pointdatshp <- rr$dmodt
rr <- rr$rr



rR <- raster::mask(rr,shapearea)

outdf <- create.df.to.plot(rR,threshold = 0)


spatialplot <- ggplot() +  
  geom_tile(data=outdf, aes(x=x, y=y, fill=value), alpha=0.8) +
  geom_polygon(aes(x = long, y = lat, group = group), data = shapefileDF,fill=NA,  
               col = "black") +
  #geom_point(data=data_mod,aes(x=Lon,y=Lat),pch=19)+
  #scale_fill_viridis() +
  scale_fill_gradient2(low = "#440154FF", mid = "#21908CFF", high = "#FDE725FF",
                     midpoint = max(leg_dat$mdheight)/2,
                     limits = c(0,max(leg_dat$mdheight)),
                     expand = c(0,0)) +
    labs(fill = "Height (m)",x="",y="")+
  coord_equal() +
  ggthemes::theme_map()+
  ggtitle(unique(SppDat$month)[m]) +
  #guides(color = guide_legend(override.aes = list(size = 0.5)))
  theme(legend.position="none",
        legend.title = element_text(size = 8), 
        legend.text = element_text(size = 8),
        plot.title = element_text(size = 12, face = "bold", colour = "black"),
        axis.title = element_text(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        plot.margin = unit(c(0,-0.5,0,-0.5), unit = "cm")
  )

leg_plot <- ggplot() +  
  geom_tile(data=outdf, aes(x=x, y=y, fill=value), alpha=0.8) +
  geom_polygon(aes(x = long, y = lat, group = group), data = shapefileDF,fill=NA,  
               col = "black") +
  scale_fill_gradient2(low = "#440154FF", mid = "#21908CFF", high = "#FDE725FF",
                     midpoint = max(leg_dat$mdheight)/2,
                     limits = c(0,max(leg_dat$mdheight)))+
  labs(fill = "Height (m)",x="Longitude",y="Latitude")

}

test_leg <- cowplot::get_legend(leg_plot + 
                                  theme(legend.position = "right"))

plot.list[[m]] <- spatialplot
}
```
```{r make_spatialplot, echo = FALSE, warning = FALSE, message = FALSE, verbose = FALSE, fig.height = 4.5, fig.width = 10}


plot_grid(ggarrange(plot.list[[1]], plot.list[[2]], plot.list[[3]], plot.list[[4]], plot.list[[5]], plot.list[[6]], plot.list[[7]], plot.list[[8]], plot.list[[9]],ncol = 4, nrow = 3), test_leg, ncol = 2, rel_widths = c(1, 0.1))

fig_num <-  run_autonum(seq_id = "Figure", pre_label = "Figure ", bkm = paste0("spatialplot_", i_sp))
  
block_caption(label = paste0("Two-dimensional spatial variation in estimated mean flight heights of ", i, " in ", yrs[k], " at site ", locs[j], ". Flight height estimates were derived using an inverse distance weighted interpolation. Grey plots indicate months were no birds of this species were recorded."), 
                style = "caption", autonum = fig_num)
```